services:
  app:
    build: .
    restart: always
    container_name: SpringBootRabbitMqBasics
    ports:
      - ${APP_PORT}:9099
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: SpringBootRabbitMqBasics-RabbitMQ
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MGT_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}


